// Interface strings rendered after page load. Keep API values and identifiers Dutch/unchanged.
export const englishDynamic = {
  'Versturen is niet gelukt. Probeer het later opnieuw.': 'Your message could not be sent. Please try again later.',
  'Menu sluiten': 'Close menu',
  'Broodkruimel': 'Breadcrumb',
  'Over ons': 'About us',
  'Redactie ZOL Solutions': 'ZOL Solutions editorial team',
  '2 september 2026': '2 September 2026',
  '1 september 2026': '1 September 2026',
  'De medische basisinformatie op deze pagina is gecontroleerd aan de hand van openbare informatie van:': 'The basic medical information on this page has been checked against public information from:',
  'Privacyvoorkeur': 'Privacy preference',
  'Jouw privacy, jouw keuze.': 'Your privacy, your choice.',
  'We gebruiken noodzakelijke browseropslag voor je winkelwagen en veilig afrekenen. Met jouw toestemming meten we beperkte gebruiksgegevens in eigen beheer en met Google Analytics om de website te verbeteren. We gebruiken geen advertentiecookies.': 'We use necessary browser storage for your basket and secure checkout. With your consent, we collect limited usage data ourselves and through Google Analytics to improve the website. We do not use advertising cookies.',
  'Lees hoe we cookies en browseropslag gebruiken': 'Read how we use cookies and browser storage',
  'Cookiekeuze': 'Cookie choice',
  'Alleen noodzakelijk': 'Necessary only',
  'Alles accepteren': 'Accept all',
  'Huidige keuze: noodzakelijke opslag en analytics.': 'Current choice: necessary storage and analytics.',
  'Huidige keuze: alleen noodzakelijke opslag.': 'Current choice: necessary storage only.',
  'Bericht versturen…': 'Sending message…',
  'Bedankt! Je bericht is ontvangen. We nemen zo snel mogelijk contact met je op.': 'Thank you! We have received your message and will get back to you as soon as possible.',
  'Bedankt! Je bericht is rechtstreeks naar ZOL Solutions verstuurd.': 'Thank you! Your message has been sent directly to ZOL Solutions.',
  'Versturen is niet gelukt. Probeer het opnieuw of mail naar info@zolsolutions.nl.': 'Your message could not be sent. Please try again or email info@zolsolutions.nl.',
  'Deze maten zijn momenteel uitverkocht.': 'These sizes are currently sold out.',
  'Voor deze maat zijn geen twee paar meer beschikbaar.': 'Two pairs are no longer available in this size.',
  'Voorraad laden duurde te lang.': 'Loading stock took too long.',
  'Voorraad opnieuw laden…': 'Reloading stock…',
  'Product niet gevonden.': 'Product not found.',
  'De voorraad kon niet worden geladen. Tik op een bestelknop om het opnieuw te proberen.': 'Stock could not be loaded. Select an order button to try again.',
  'Een moment, de voorraad wordt geladen…': 'One moment, stock is loading…',
  'Kies een beschikbare maat om verder te gaan.': 'Choose an available size to continue.',
  'Toegevoegd ✓': 'Added ✓',
  'Deze maat is inmiddels weer op voorraad.': 'This size is now back in stock.',
  'Vul een geldig e-mailadres in.': 'Enter a valid email address.',
  'Aanmelden…': 'Signing up…',
  'Aanmelden lukt nu niet. Probeer het straks opnieuw.': 'We could not sign you up. Please try again later.',
  'Je staat al op de lijst voor deze maat. We laten het weten zodra hij er weer is.': 'You are already on the list for this size. We will let you know when it is back.',
  'Gelukt! We mailen je één keer zodra deze maat weer op voorraad is.': 'Done! We will email you once when this size is back in stock.',
  'Betaal direct via je eigen bank': 'Pay directly through your bank',
  'Creditcard': 'Credit card',
  'Visa, Mastercard en meer': 'Visa, Mastercard and more',
  'Snel betalen met je Apple-apparaat': 'Pay quickly with your Apple device',
  'Betaal met je PayPal-account': 'Pay with your PayPal account',
  'Veilig betalen vanuit België': 'Secure payments from Belgium',
  'Bankoverschrijving': 'Bank transfer',
  'Handmatig via je bank': 'Manually through your bank',
  'Betaal in drie delen': 'Pay in three instalments',
  'Betaal met Klarna': 'Pay with Klarna',
  'België · 2–4 werkdagen': 'Belgium · 2–4 working days',
  'Je kiest je betaalmethode in de volgende stap.': 'Choose your payment method in the next step.',
  'Automatische korting': 'Automatic discount',
  'Korting': 'Discount',
  'Na het plaatsen van je bestelling reken je veilig af in de betaalomgeving van Mollie.': 'After placing your order, you will pay securely in Mollie’s payment environment.',
  'Je bestelling wordt veilig vastgelegd. ZOL neemt persoonlijk contact met je op over de betaling.': 'Your order will be securely recorded. ZOL will contact you personally about payment.',
  'Besteloverzicht': 'Order summary',
  'Subtotaal': 'Subtotal',
  'Verzending': 'Delivery',
  'Gratis': 'Free',
  'Totaal': 'Total',
  'Automatisch toegepast': 'Applied automatically',
  'Kortingscode toegepast': 'Discount code applied',
  'Controleren…': 'Checking…',
  'Kortingscode controleren…': 'Checking discount code…',
  'Prijs opnieuw berekenen…': 'Recalculating price…',
  'De kortingscode kon niet worden gecontroleerd.': 'The discount code could not be checked.',
  'De code is geldig, maar levert bij deze bestelling geen extra korting op.': 'The code is valid but does not provide an additional discount for this order.',
  'Je winkelwagen is leeg': 'Your basket is empty',
  "Kies eerst de juiste maat ZOL'tjes.": 'First choose the right size of ZOL insoles.',
  'Bekijk het product': 'View the product',
  'Overzicht': 'Summary',
  'Controleer de maat en het aantal.': 'Check the size and quantity.',
  'Aantal aanpassen': 'Adjust quantity',
  'Aantal verlagen': 'Decrease quantity',
  'Aantal verhogen': 'Increase quantity',
  'Verwijder': 'Remove',
  'ZOL 3/4 inlegzolen': 'ZOL 3/4 insoles',
  'Betaling controleren': 'Checking payment',
  'Een ogenblik, we controleren de actuele betaalstatus.': 'One moment, we are checking the current payment status.',
  'Controleren': 'Checking',
  'Sluit deze pagina nog niet.': 'Please keep this page open.',
  'Status niet beschikbaar': 'Status unavailable',
  'We konden de betaling niet automatisch controleren. Neem contact op met ZOL en vermeld je bestelnummer.': 'We could not check the payment automatically. Please contact ZOL and include your order number.',
  'Hulp nodig?': 'Need help?',
  'We zoeken je bestelling graag persoonlijk voor je op.': 'We will be happy to look up your order for you.',
  'Betaling gelukt': 'Payment successful',
  'Betaling wordt verwerkt': 'Payment is being processed',
  'Betaling niet afgerond': 'Payment not completed',
  'Bestelling ontvangen': 'Order received',
  'Bedankt! Je bestelling is betaald en staat klaar voor verwerking.': 'Thank you! Your order has been paid for and is ready to be processed.',
  'De betaalstatus is nog niet definitief. ZOL verwerkt je bestelling zodra Mollie de betaling bevestigt.': 'The payment status is not yet final. ZOL will process your order once Mollie confirms payment.',
  'Je bestelling bestaat nog, maar de betaling is niet gelukt of afgebroken. Je kunt de betaling veilig opnieuw starten.': 'Your order still exists, but the payment failed or was cancelled. You can safely restart the payment.',
  'Opnieuw betalen →': 'Retry payment →',
  'Bewaar dit bestelnummer voor vragen over je bestelling.': 'Keep this order number for any questions about your order.',
  'Betaallink openen…': 'Opening payment link…',
  'Opnieuw betalen is niet gelukt. Neem contact op met ZOL.': 'The payment could not be restarted. Please contact ZOL.',
  'Klik op toepassen om je code te controleren.': 'Select Apply to check your code.',
  'Geef aan hoe je bij ZOL Solutions bent terechtgekomen.': 'Tell us how you heard about ZOL Solutions.',
  'Vertel hoe je ons hebt gevonden om verder te gaan.': 'Tell us how you found us to continue.',
  'Vink eerst aan dat je akkoord gaat met de voorwaarden en het privacybeleid.': 'Please tick the box to accept the terms and privacy policy.',
  'Vul een geldige Belgische postcode van vier cijfers in.': 'Enter a valid four-digit Belgian postcode.',
  'Vul een geldige Nederlandse postcode in, bijvoorbeeld 1234 AB.': 'Enter a valid Dutch postcode, for example 1234 AB.',
  'Controleer de gemarkeerde velden en vul alle verplichte gegevens in.': 'Check the highlighted fields and complete all required details.',
  'Bestelling verwerken…': 'Processing order…',
  'Controleer eerst de kortingscode hierboven.': 'Please check the discount code above first.',
  'De actuele prijs kon niet worden gecontroleerd. Probeer het opnieuw.': 'The current price could not be checked. Please try again.',
  'Afrekenen is niet gelukt.': 'Checkout was unsuccessful.',
  'Afrekenen is niet gelukt. Probeer het opnieuw.': 'Checkout was unsuccessful. Please try again.',
  'Je bestelling staat veilig in ZOL Admin. Online betalen wordt geactiveerd zodra Mollie is gekoppeld; ZOL neemt tot die tijd persoonlijk contact met je op over de betaling.': 'Your order has been securely recorded in ZOL Admin. Online payments will be activated once Mollie is connected; until then, ZOL will contact you personally about payment.',
  'Ontvangen': 'Received',
  'Deze afmeldlink is niet geldig. Je kunt ons ook mailen via info@zolsolutions.nl.': 'This unsubscribe link is not valid. You can also email us at info@zolsolutions.nl.',
  'Afmelden…': 'Unsubscribing…',
  'Afmelden is niet gelukt. Probeer het nog een keer of mail info@zolsolutions.nl.': 'Unsubscribing was unsuccessful. Please try again or email info@zolsolutions.nl.',
  'Opnieuw proberen': 'Try again',
  'Je bent afgemeld. Je ontvangt geen driewekelijkse producttips meer van ZOL Solutions.': 'You have unsubscribed. You will no longer receive product tips from ZOL Solutions every three weeks.',
  'Je stond al afgemeld.': 'You were already unsubscribed.',
  'Afmelding opgeslagen.': 'You have been unsubscribed.',
}

export const englishPatterns = [
  [/^Niet genoeg voorraad voor (.+)\.$/, (_, product) => `Not enough stock for ${product.replace('inlegzolen', 'insoles')}.`],
  [/^Besteed minimaal €(.+) om deze kortingscode te gebruiken\.$/, (_, amount) => `Spend at least €${amount} to use this discount code.`],
  [/^Op voorraad — maat (.+)$/, (_, size) => `In stock — size ${size}`],
  [/^Nog maar (\d+) op voorraad — maat (.+)$/, (_, count, size) => `Only ${count} left in stock — size ${size}`],
  [/^Maat (.+) is uitverkocht\.$/, (_, size) => `Size ${size} is sold out.`],
  [/^Maat (.+) is uitverkocht — kies deze maat voor een voorraadmelding$/, (_, size) => `Size ${size} is sold out — select it for a stock notification`],
  [/^Maat (.+), schoenmaat (.+?)(, uitverkocht)?$/, (_, size, shoe, sold) => `Size ${size}, shoe size ${shoe}${sold ? ', sold out' : ''}`],
  [/^Ontvang een seintje voor maat (.+)$/, (_, size) => `Get notified for size ${size}`],
  [/^Aantal (\d+)$/, (_, count) => `Quantity ${count}`],
  [/^(.+) per paar$/, (_, price) => `${price} per pair`],
  [/^ZOL (.+) verwijderen$/, (_, name) => `Remove ZOL ${name.replace('inlegzolen', 'insoles')}`],
  [/^Korting\s*(\(.+\))$/, (_, code) => `Discount ${code}`],
  [/^Bestelling #(.+) is ontvangen$/, (_, number) => `Order #${number} received`],
  [/^Bestelling #(.+)$/, (_, number) => `Order #${number}`],
  [/^Bewaar bestelnummer #(.+) voor vragen over je bestelling\.$/, (_, number) => `Keep order number #${number} for any questions about your order.`],
  [/^(Automatische korting|Code .+) toegepast — (.+)\.$/, (_, label, saving) => `${label === 'Automatische korting' ? 'Automatic discount' : label} applied — ${saving.replace(' korting', ' off').replace('geldig voor deze bestelling', 'valid for this order')}.`],
]
